# Generated by Django 3.1.7 on 2022-01-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilteredCharacters',
        ),
    ]
